repo_url: "https://markcs.github.io/mcs-fdroid/repo"
repo_name: "mcs f-droid repo"
repo_description: >-
  Custom Android app repository hosted on GitHub Pages.

# Keystore configuration
keystore: "keystore.p12"
repo_keyalias: "repo_key"

# Dummy values to satisfy fdroidserver's config check.
# The real values are overridden on the CLI below.
keystorepass: "dummy"
keypass: "dummy"

allow_unsigned_apks: true
