repo_url: "https://markcs.github.io/mcs-fdroid/repo"
repo_name: "mcs f-droid repo"
repo_description: >-
  Custom Android app repository hosted on GitHub Pages.

keystore: "keystore.p12"
repo_keyalias: "repo_key"

# Use environment variables
keystorepass: "env FDROID_KEY_STORE_PASS"
keypass: "env FDROID_KEY_PASS"

allow_unsigned_apks: true
