repo_url: "https://markcs.github.io/mcs-fdroid/repo"
repo_name: "mcs f-droid repo"
repo_icon: "icon.png"
repo_description: >-
  Custom Android app repository hosted on GitHub Pages.

keystore: "keystore.p12"
repo_keyalias: "repo_key"

# Uses bash-style environment variable expansion supported by Python's fdroidserver
keystorepass: "$KEYSTORE_PASSWORD"
keypass: "$KEY_PASSWORD"

allow_unsigned_apks: true
